### ISSUE TITLE
Fails to parse "Clash of the Princes"

### ISSUE THREAD

**Issue by pak21** [lcosmin/boardgamegeek#47]
Attempting to fetch "Clash of the Princes" (ID 54165) results in an exception; trivial test case is `BGGClient().game(game_id = 54165)`:

Traceback (most recent call last):
  File "./get-bgg-game.py", line 5, in <module>
    BGGClient().game(game_id = 54165)
  File "/home/philip/.local/lib/python3.6/site-packages/boardgamegeek/api.py", line 845, in game
    html_parser=html_parser)
  File "/home/philip/.local/lib/python3.6/site-packages/boardgamegeek/loaders/game.py", line 217, in create_game_from_xml
    return BoardGame(data)
  File "/home/philip/.local/lib/python3.6/site-packages/boardgamegeek/objects/games.py", line 924, in __init__
    super(BoardGame, self).__init__(data)
  File "/home/philip/.local/lib/python3.6/site-packages/boardgamegeek/objects/games.py", line 567, in __init__
    self._year_published = fix_unsigned_negative(data["yearpublished"])
  File "/home/philip/.local/lib/python3.6/site-packages/boardgamegeek/utils.py", line 389, in fix_unsigned_negative
    if value > 0x7FFFFFFF:
TypeError: '>' not supported between instances of 'NoneType' and 'int'

From eyeballing the XML, I suspect this is because the release year is just entirely unset: `<yearpublished value="" />`.

**Comment by pak21** [comment]
PR hopefully incoming in the next couple of days unless this turns out to be much harder to fix than I expect.

**Comment by pak21** [comment]
Sorry, seems this was fixed a long time ago but my package management had got screwed up. Please ignore the noise.
